# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Benbentwo.com
title: Benbentwo
email: ben.smith.developer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tech tips and other cool things.
url: https://benbentwo.com
teaser: /assets/images/contribution.svg
logo: /assets/images/favicons/android-chrome-192x192.png
breadcrumbs: true
twitter_username: username
github_username: Benbentwo
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: Benbentwo/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

analytics:
  provider               : google # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : UA-173923242-1
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Benjamin Smith"
  avatar : "/assets/images/IMG_1414.JPG"
  bio    : "DevOps Engineer; making sites, games, and OSS"
  links:
    - label: "Benbentwo"
      icon: "fas fa-fw fa-link"
      url: "https://Benbentwo.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Benbentwo"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/benjamin-smith-15378010a/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Benbentwo"
    - label: "Benbentwo"
      icon: "fas fa-fw fa-link"
      url: "https://Benbentwo.com/"
    - label: "Email"
      url: "mailto:ben.smith.developer@gmail.com"
      icon: "fas fa-envelope"
    - label: "Source"
      url: "https://github.com/Benbentwo/dot-com"
      icon: "fas fa-desktop"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
